- project:
    templates:
      - check-requirements
      - designate-devstack-jobs
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
