- project:
    templates:
      - check-requirements
      - designate-devstack-jobs
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
    queue: designate
