- project:
    templates:
      - check-requirements
      - designate-devstack-jobs
      - openstack-cover-jobs
      - openstack-python3-zed-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    queue: designate
